[workspace]
members = [
    "crates/proto",
    "crates/core",
    "crates/server",
    "crates/client",
]
resolver = "2"

[workspace.package]
edition = "2024"

[profile.release]
lto = true
panic = "abort"
