name: Rust CI

on:
  pull_request:
    branches: [ main ] # Or your default branch

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Install formatting and lint tools
        run: rustup component add rustfmt clippy

      - name: Check formatting
        run: cargo fmt --all --check

      - name: Run clippy
        run: cargo clippy --all-targets -- -D warnings

      - name: Run cargo test
        run: cargo test
